import { MigrationInterface, QueryRunner } from "typeorm";

export class UsersAndOthers1762857955268 implements MigrationInterface {
    name = 'UsersAndOthers1762857955268'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cars"."message_contents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content" text NOT NULL, "attachments" jsonb NOT NULL DEFAULT '[]', "version" integer NOT NULL DEFAULT '1', "messageId" uuid, CONSTRAINT "PK_03279c256f7af6160464f6a1515" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content" text NOT NULL, "attachments" jsonb NOT NULL DEFAULT '[]', "voiceUrl" character varying, "type" character varying NOT NULL DEFAULT 'text', "isRead" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "quotedText" text, "chatId" uuid, "senderId" uuid, "current_content_id" uuid, "replied_message_id" uuid, "forwarded_from_id" uuid, CONSTRAINT "REL_08f16c5d53571d16195e43a9a0" UNIQUE ("current_content_id"), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."unread_chats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "unreadCount" integer NOT NULL DEFAULT '0', "userId" uuid, "chatId" uuid, CONSTRAINT "PK_2d0badc60fed194efdb9af98a7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_762873d081b5d6c6c146710fcf" ON "cars"."unread_chats" ("userId", "chatId") `);
        await queryRunner.query(`CREATE TABLE "cars"."chats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" character varying NOT NULL DEFAULT 'private', "name" character varying, "description" character varying, "uniqueKey" character varying NOT NULL, "lastMessageId" uuid, "createdById" uuid, CONSTRAINT "UQ_85dfa7b940bde947a406940de34" UNIQUE ("uniqueKey"), CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_chat_created_at" ON "cars"."chats" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_chat_updated_at" ON "cars"."chats" ("updatedAt") `);
        await queryRunner.query(`CREATE INDEX "idx_chat_unique_key" ON "cars"."chats" ("uniqueKey") `);
        await queryRunner.query(`CREATE TABLE "cars"."reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content" character varying(200) NOT NULL, "answer" character varying(200), "answeredAt" TIMESTAMP WITH TIME ZONE, "rank" integer NOT NULL, "images" jsonb NOT NULL DEFAULT '[]', "isVerified" boolean NOT NULL DEFAULT false, "authorId" uuid, "userId" uuid, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, "subscribed_user_id" uuid, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."followers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "follower_id" uuid, "subscribed_user_id" uuid, CONSTRAINT "PK_c90cfc5b18edd29bd15ba95c1a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" character varying NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "userId" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cars"."user_block" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid, "blockedUserId" uuid, CONSTRAINT "PK_4ccc8015091b2f9054ce0e40db5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_block_created_at" ON "cars"."user_block" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_user_block_updated_at" ON "cars"."user_block" ("updatedAt") `);
        await queryRunner.query(`CREATE TABLE "cars"."chat_users" ("chat_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_31efa25a44c55b3ceed47f98ba4" PRIMARY KEY ("chat_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f60265ed6da63600bad2c5ee8c" ON "cars"."chat_users" ("chat_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a5f2493e2c02490ceb527649e" ON "cars"."chat_users" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "cars"."favorite_chats" ("user_id" uuid NOT NULL, "chat_id" uuid NOT NULL, CONSTRAINT "PK_77a1a21755755ca0f3277cf8813" PRIMARY KEY ("user_id", "chat_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_01fb6b75feeed8947ff7af6373" ON "cars"."favorite_chats" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_691ea633dcc15524c68040881d" ON "cars"."favorite_chats" ("chat_id") `);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "deletedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "rating" double precision`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "isDeactivated" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" DROP CONSTRAINT "PK_b791c2dc91b2f3d3608b3acb29f"`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" ADD CONSTRAINT "PK_b791c2dc91b2f3d3608b3acb29f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP CONSTRAINT "PK_7d8bee0204106019488c4c50ffa"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cars"."message" DROP CONSTRAINT "FK_bc096b4e18b1f9508197cd98066"`);
        await queryRunner.query(`ALTER TABLE "cars"."message" DROP CONSTRAINT "FK_619bc7b78eba833d2044153bacc"`);
        await queryRunner.query(`ALTER TABLE "cars"."chat" DROP CONSTRAINT "FK_94b99bfa9e0c52a67b5ca71e53d"`);
        await queryRunner.query(`ALTER TABLE "cars"."chat" DROP CONSTRAINT "FK_928d33ac6fe5d505cbc21b46511"`);
        await queryRunner.query(`DROP TABLE "cars"."message"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_8febe36332a28b664a2b2434fa"`);
        await queryRunner.query(`DROP TABLE "cars"."chat"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "nickname" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023" UNIQUE ("nickname")`);
        await queryRunner.query(`ALTER TABLE "cars"."message_contents" ADD CONSTRAINT "FK_9d82e8565547b2bb2c975e4f8b3" FOREIGN KEY ("messageId") REFERENCES "cars"."messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" ADD CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115" FOREIGN KEY ("chatId") REFERENCES "cars"."chats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" ADD CONSTRAINT "FK_08f16c5d53571d16195e43a9a04" FOREIGN KEY ("current_content_id") REFERENCES "cars"."message_contents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" ADD CONSTRAINT "FK_fa6db99f5f890b9c9e8260e35d9" FOREIGN KEY ("replied_message_id") REFERENCES "cars"."messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" ADD CONSTRAINT "FK_ac6b12ef0b3f9ac9d522bd0d6e2" FOREIGN KEY ("forwarded_from_id") REFERENCES "cars"."messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."unread_chats" ADD CONSTRAINT "FK_e00abd209eae688e408b210ac99" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."unread_chats" ADD CONSTRAINT "FK_1f2aac16dfcc98bc852fb2d4076" FOREIGN KEY ("chatId") REFERENCES "cars"."chats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."chats" ADD CONSTRAINT "FK_5768a56bdd855c5b78ce66c9a37" FOREIGN KEY ("lastMessageId") REFERENCES "cars"."messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."chats" ADD CONSTRAINT "FK_fa7cbf53930e01a370b3841a1bc" FOREIGN KEY ("createdById") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."reviews" ADD CONSTRAINT "FK_48770372f891b9998360e4434f3" FOREIGN KEY ("authorId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."subscriptions" ADD CONSTRAINT "FK_8d3d7c9ab9bc6db519fd2d147e8" FOREIGN KEY ("subscribed_user_id") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."followers" ADD CONSTRAINT "FK_e11d02e2a1197cfb61759da5a87" FOREIGN KEY ("follower_id") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."followers" ADD CONSTRAINT "FK_dae4b5a8d33611fc43bb3a9674d" FOREIGN KEY ("subscribed_user_id") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."user_block" ADD CONSTRAINT "FK_d1a5c2390a4f7c1193bc1dde183" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."user_block" ADD CONSTRAINT "FK_f8d3ed19d5a271bb6025aedb8e7" FOREIGN KEY ("blockedUserId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."chat_users" ADD CONSTRAINT "FK_f60265ed6da63600bad2c5ee8c4" FOREIGN KEY ("chat_id") REFERENCES "cars"."chats"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cars"."chat_users" ADD CONSTRAINT "FK_9a5f2493e2c02490ceb527649e4" FOREIGN KEY ("user_id") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."favorite_chats" ADD CONSTRAINT "FK_01fb6b75feeed8947ff7af63734" FOREIGN KEY ("user_id") REFERENCES "cars"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cars"."favorite_chats" ADD CONSTRAINT "FK_691ea633dcc15524c68040881d0" FOREIGN KEY ("chat_id") REFERENCES "cars"."chats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cars"."favorite_chats" DROP CONSTRAINT "FK_691ea633dcc15524c68040881d0"`);
        await queryRunner.query(`ALTER TABLE "cars"."favorite_chats" DROP CONSTRAINT "FK_01fb6b75feeed8947ff7af63734"`);
        await queryRunner.query(`ALTER TABLE "cars"."chat_users" DROP CONSTRAINT "FK_9a5f2493e2c02490ceb527649e4"`);
        await queryRunner.query(`ALTER TABLE "cars"."chat_users" DROP CONSTRAINT "FK_f60265ed6da63600bad2c5ee8c4"`);
        await queryRunner.query(`ALTER TABLE "cars"."user_block" DROP CONSTRAINT "FK_f8d3ed19d5a271bb6025aedb8e7"`);
        await queryRunner.query(`ALTER TABLE "cars"."user_block" DROP CONSTRAINT "FK_d1a5c2390a4f7c1193bc1dde183"`);
        await queryRunner.query(`ALTER TABLE "cars"."notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "cars"."followers" DROP CONSTRAINT "FK_dae4b5a8d33611fc43bb3a9674d"`);
        await queryRunner.query(`ALTER TABLE "cars"."followers" DROP CONSTRAINT "FK_e11d02e2a1197cfb61759da5a87"`);
        await queryRunner.query(`ALTER TABLE "cars"."subscriptions" DROP CONSTRAINT "FK_8d3d7c9ab9bc6db519fd2d147e8"`);
        await queryRunner.query(`ALTER TABLE "cars"."subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "cars"."reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "cars"."reviews" DROP CONSTRAINT "FK_48770372f891b9998360e4434f3"`);
        await queryRunner.query(`ALTER TABLE "cars"."chats" DROP CONSTRAINT "FK_fa7cbf53930e01a370b3841a1bc"`);
        await queryRunner.query(`ALTER TABLE "cars"."chats" DROP CONSTRAINT "FK_5768a56bdd855c5b78ce66c9a37"`);
        await queryRunner.query(`ALTER TABLE "cars"."unread_chats" DROP CONSTRAINT "FK_1f2aac16dfcc98bc852fb2d4076"`);
        await queryRunner.query(`ALTER TABLE "cars"."unread_chats" DROP CONSTRAINT "FK_e00abd209eae688e408b210ac99"`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" DROP CONSTRAINT "FK_ac6b12ef0b3f9ac9d522bd0d6e2"`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" DROP CONSTRAINT "FK_fa6db99f5f890b9c9e8260e35d9"`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" DROP CONSTRAINT "FK_08f16c5d53571d16195e43a9a04"`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "cars"."messages" DROP CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115"`);
        await queryRunner.query(`ALTER TABLE "cars"."message_contents" DROP CONSTRAINT "FK_9d82e8565547b2bb2c975e4f8b3"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "nickname"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "nickname" character varying`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD CONSTRAINT "UQ_ad02a1be8707004cb805a4b5023" UNIQUE ("nickname")`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cars"."users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP CONSTRAINT "PK_7d8bee0204106019488c4c50ffa"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "cars"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" DROP CONSTRAINT "PK_b791c2dc91b2f3d3608b3acb29f"`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cars"."sms_verifications" ADD CONSTRAINT "PK_b791c2dc91b2f3d3608b3acb29f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "isDeactivated"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "cars"."users" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_691ea633dcc15524c68040881d"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_01fb6b75feeed8947ff7af6373"`);
        await queryRunner.query(`DROP TABLE "cars"."favorite_chats"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_9a5f2493e2c02490ceb527649e"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_f60265ed6da63600bad2c5ee8c"`);
        await queryRunner.query(`DROP TABLE "cars"."chat_users"`);
        await queryRunner.query(`DROP INDEX "cars"."idx_user_block_updated_at"`);
        await queryRunner.query(`DROP INDEX "cars"."idx_user_block_created_at"`);
        await queryRunner.query(`DROP TABLE "cars"."user_block"`);
        await queryRunner.query(`DROP TABLE "cars"."notifications"`);
        await queryRunner.query(`DROP TABLE "cars"."followers"`);
        await queryRunner.query(`DROP TABLE "cars"."subscriptions"`);
        await queryRunner.query(`DROP TABLE "cars"."reviews"`);
        await queryRunner.query(`DROP INDEX "cars"."idx_chat_unique_key"`);
        await queryRunner.query(`DROP INDEX "cars"."idx_chat_updated_at"`);
        await queryRunner.query(`DROP INDEX "cars"."idx_chat_created_at"`);
        await queryRunner.query(`DROP TABLE "cars"."chats"`);
        await queryRunner.query(`DROP INDEX "cars"."IDX_762873d081b5d6c6c146710fcf"`);
        await queryRunner.query(`DROP TABLE "cars"."unread_chats"`);
        await queryRunner.query(`DROP TABLE "cars"."messages"`);
        await queryRunner.query(`DROP TABLE "cars"."message_contents"`);
        await queryRunner.query(`CREATE TABLE "cars"."chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "uniqueKey" character varying NOT NULL, "lastMessageContent" character varying, "lastMessageCreatedAt" TIMESTAMP, "unreadCountForUserA" integer NOT NULL DEFAULT '0', "unreadCountForUserB" integer NOT NULL DEFAULT '0', "userAId" integer, "userBId" integer, CONSTRAINT "UQ_8febe36332a28b664a2b2434fad" UNIQUE ("uniqueKey"), CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8febe36332a28b664a2b2434fa" ON "cars"."chat" ("uniqueKey") `);
        await queryRunner.query(`CREATE TABLE "cars"."message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content" text NOT NULL, "attachments" jsonb NOT NULL DEFAULT '[]', "isRead" boolean NOT NULL DEFAULT false, "isDeleted" boolean NOT NULL DEFAULT false, "chatId" uuid, "senderId" integer, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cars"."chat" ADD CONSTRAINT "FK_928d33ac6fe5d505cbc21b46511" FOREIGN KEY ("userAId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."chat" ADD CONSTRAINT "FK_94b99bfa9e0c52a67b5ca71e53d" FOREIGN KEY ("userBId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."message" ADD CONSTRAINT "FK_619bc7b78eba833d2044153bacc" FOREIGN KEY ("chatId") REFERENCES "cars"."chat"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars"."message" ADD CONSTRAINT "FK_bc096b4e18b1f9508197cd98066" FOREIGN KEY ("senderId") REFERENCES "cars"."users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
