FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn config set network-timeout 600000 -g && \
    yarn install --frozen-lockfile --verbose
COPY . .

CMD ["yarn", "migration:run"]
