services:
  postgres-cars:
    container_name: postgres-cars
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cars:
    container_name: redis-cars
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  cars-backend:
    container_name: cars-backend
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - postgres-cars
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/simpleit-gitlab.ru/fullchain.pem:/app/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/simpleit-gitlab.ru/privkey.pem:/app/ssl/private/privkey.pem:ro

networks:
  default:
    driver: bridge
    driver_opts:
      # нужно для того, чтобы корректно устанавливались зависимости во время билда
      com.docker.network.driver.mtu: 1428

volumes:
  postgres_data:
  redis_data:
